name: Development CD

on:
  repository_dispatch:
    types: [dev-ais-app-repository-dispatch]

env:
  DOTNET_CLI_HOME: "/home/azureuser"
  HOME: "/home/azureuser"

jobs:
  build:
    runs-on: self-hosted:dev

    steps:
      - run: echo ${{ github.event.client_payload.github_sha }}

      - uses: actions/checkout@v2
        with:
            ref: develop

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ./build-output

      - name: Upload artifact for deployment job
        run: |
          zip artifact-${GITHUB_SHA}.zip -r ./build-output
          rm -rf ./build-output
          az storage blob upload -c build -n artifact-${GITHUB_SHA}.zip -f ${GITHUB_WORKSPACE}/artifact-${GITHUB_SHA}.zip --connection-string "${{ secrets.BUILD_STORAGE_ACCOUNT_CONNECTION_STRING }}"
          rm artifact-${GITHUB_SHA}.zip
          
      - name: Save artifact name to main branch
        run: |
          echo "artifact-${GITHUB_SHA}.zip" > latest-build-artifact
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "save latest artifact build name on Dev workflow"
          git push

  deploy:
    runs-on: self-hosted:dev
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2
        with:
            ref: develop

      - name: Download artifact from build job
        run: |
          export ARTIFACT_NAME=$(cat latest-build-artifact)
          az storage blob download -c "build" -n ${ARTIFACT_NAME} -f ${GITHUB_WORKSPACE}/${ARTIFACT_NAME} --connection-string "${{ secrets.BUILD_STORAGE_ACCOUNT_CONNECTION_STRING }}"
          unzip ${ARTIFACT_NAME}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ais-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_87241CB7D83A4C6B925F284A4955F252 }}
          package: ./build-output