name: SIT CI

on:
  push:
    tags:
      - "*.*.*"


jobs:

  dispatch-repository:
    if: github.event.base_ref=='refs/heads/main'

    name: Dispatch repository

    runs-on: self-hosted:sit

    steps:
      - name: Repository dispatch
        run: |
          curl -v --location --request POST 'https://api.github.com/repos/kubeops-learning/ais-app/dispatches' \
            --header 'Authorization: Bearer ${{ secrets.DISPATCHER_TOKEN }}' \
            --header 'accept: application/vnd.github.v3+json' \
            --header 'Content-Type: application/json' \
            --data-raw '{"event_type":"sit-ais-app-repository-dispatch"}'
