name: SIT CI

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags'
        required: true 

jobs:

  dispatch-repository:
    if: github.event.base_ref=='refs/heads/main'

    name: Dispatch repository

    runs-on: ubuntu-20.04

    steps:
      - name: Repository dispatch
        run: |
          curl -v --location --request POST 'https://api.github.com/repos/kubeopsskills-enterprise/man-app-pipeline/dispatches' \
            --header 'Authorization: Bearer ${{ secrets.DISPATCHER_TOKEN }}' \
            --header 'accept: application/vnd.github.v3+json' \
            --header 'Content-Type: application/json' \
            --data-raw '{"event_type":"sit-ais-app-repository-dispatch"}'
