name: SIT CD

on:
  repository_dispatch:
    types: [sit-ais-app-repository-dispatch]

env:
  DOTNET_CLI_HOME: "/home/azureuser"
  HOME: "/home/azureuser"

jobs:
  deploy:
    runs-on: self-hosted:sit
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2
        with:
            ref: main
            
      - name: Download artifact from build job
        run: |
          export ARTIFACT_NAME=$(cat latest-build-artifact)
          az storage blob download -c "build" -n ${ARTIFACT_NAME} -f ${GITHUB_WORKSPACE}/${ARTIFACT_NAME} --connection-string "${{ secrets.BUILD_STORAGE_ACCOUNT_CONNECTION_STRING }}"
          unzip ${ARTIFACT_NAME}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ais-sit'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BEFA5B81DB7A43FB80E71E0167AEDCD2 }}
          package: ./build-output

  dispatch-repository:
    needs: deploy
    name: Dispatch repository

    runs-on: self-hosted:sit

    steps:
      - name: Repository dispatch
        run: |
          curl -v --location --request POST 'https://api.github.com/repos/kubeopsskills-enterprise/man-app/dispatches' \
            --header 'Authorization: Bearer ${{ secrets.DISPATCHER_TOKEN }}' \
            --header 'accept: application/vnd.github.v3+json' \
            --header 'Content-Type: application/json' \
            --data-raw '{"event_type":"uat-ci-repository-dispatch"}'
