name: Review by VA/PT security team

on:
  repository_dispatch:
    types: [review-by-va-pt-security-team]

jobs:
  dispatch-repository:
    runs-on: self-hosted:uat
    name: Approve to transfer to Change team
    environment:
      name: 'VAPT-SECURITY'

    steps:
      - name: Repository dispatch
        run: |
          curl -v --location --request POST 'https://api.github.com/repos/kubeopsskills-enterprise/man-app/dispatches' \
            --header 'Authorization: Bearer ${{ secrets.DISPATCHER_TOKEN }}' \
            --header 'accept: application/vnd.github.v3+json' \
            --header 'Content-Type: application/json' \
            --data-raw '{"event_type":"review-by-change-team"}'
  
